export { SetupPanel } from "./setup-panel";
export { Dashboard } from "./dashboard-panel";
export { ChatPanel } from "./chat-panel";
export { ResearchPanel } from "./research-panel";
export { ConfigPanel } from "./config-panel";
export { MemoryPanel } from "./memory-panel";
export { SQLitePanel } from "./sqlite-panel";
export { PluginsPanel } from "./plugins-panel";
export { WorkbenchPanel } from "./workbench-panel";
